export const ELEMENTS = {
    menuButton: '.btn-menu',
    myProfileButton: ':nth-child(4) > .menu-link',
    ProfileEditButton: ':nth-child(4) > .submenu > :nth-child(2) > .menu-subitem-link',
    districtCombo: 'div[name=neighborhood]',
    referenceInput: 'input[name=reference]',
    searchDistrictCombo: 'div[name=search-neighborhood]',
    continueButton: '.colorful-primary',
    clientsButton: "div[class='text-select__option colorful']:nth-child(1)",
    companionDoesLabel: "label[for*='acompanhantedoes']:nth-child(1)",
    favCompanionDoesService: "#edit-ad-profile > div > div.price-data > div.services-list > div:nth-child(1) > div > div.service__description > div.service__two-column > div.fm-button:nth-child(2)",
    companionDoesDescription: "#edit-ad-profile > div > div.price-data > div.services-list > div:nth-child(1) > div > div.service__description",
    mouthKissDoesLabel: "label[for*='beijo-na-bocadoes']:nth-child(1)",
    favMouthKissDoesService: "#edit-ad-profile > div > div.price-data > div.services-list > div:nth-child(3) > div > div.service__description > div.service__two-column > div.fm-button:nth-child(2)",
    mouthKissDoesDescription: "#edit-ad-profile > div > div.price-data > div.services-list > div:nth-child(3) > div > div.service__description",
    bondageDoesLabel: "label[for*='bondagedoes']:nth-child(1)",
    favBondageDoesService: "#edit-ad-profile > div > div.price-data > div.services-list > div:nth-child(4) > div:nth-child(1) > div.service__description > div.service__two-column > div.fm-button:nth-child(2)",
    bondageDoesDescription: "#edit-ad-profile > div > div.price-data > div.services-list > div:nth-child(4) > div:nth-child(1) > div.service__description",
    bondageReceiveLabel: "label[for*=bondagereceive]:nth-child(1)",
    favBondageReceiveService: "#edit-ad-profile > div > div.price-data > div.services-list > div:nth-child(4) > div:nth-child(2) > div.service__description > div.service__two-column > div.fm-button:nth-child(2)",
    bondageReceiveDescription: "#edit-ad-profile > div > div.price-data > div.services-list > div:nth-child(4) > div:nth-child(2) > div.service__description",
    dominationDoesLabel: "label[for*=dominacaoreceive]:nth-child(1)",
    greekKissDoesLabel: "label[for*='beijo-gregodoes']:nth-child(1)",
    favGreekKissDoesService: "#edit-ad-profile > div > div.price-data > div.services-list > div:nth-child(2) > div:nth-child(1) > div.service__description > div.service__two-column > div.fm-button:nth-child(2)",
    greekKissDoesDescription: "#edit-ad-profile > div > div.price-data > div.services-list > div:nth-child(2) > div:nth-child(1) > div.service__description",
    greekKissReceiveLabel: "label[for*='beijo-gregoreceive']:nth-child(1)",
    favGreekKissReceiveService: "#edit-ad-profile > div > div.price-data > div.services-list > div:nth-child(2) > div:nth-child(2) > div.service__description > div.service__two-column > div.fm-button:nth-child(2)",
    greekKissReceiveDescription: "#edit-ad-profile > div > div.price-data > div.services-list > div:nth-child(2) > div:nth-child(2) > div.service__description",
    goldenShowerDoesLabel: "label[for*='chuva-douradadoes']:nth-child(1)",
    favGoldenShowerDoesService: "#edit-ad-profile > div > div.price-data > div.services-list > div:nth-child(5) > div:nth-child(1) > div.service__description > div.service__two-column > div.fm-button:nth-child(2)",
    goldenShowerDoesDescription: "#edit-ad-profile > div > div.price-data > div.services-list > div:nth-child(5) > div:nth-child(1) > div.service__description",
    goldenShowerReceiveLabel: "label[for*='chuva-douradareceive']:nth-child(1)",
    favGoldenShowerReceiveService: "#edit-ad-profile > div > div.price-data > div.services-list > div:nth-child(5) > div:nth-child(2) > div.service__description > div.service__two-column > div.fm-button:nth-child(2)",
    goldenShowerReceiveDescription: "#edit-ad-profile > div > div.price-data > div.services-list > div:nth-child(5) > div:nth-child(2) > div.service__description",
    favDominationDoesService: "#edit-ad-profile > div > div.price-data > div.services-list > div:nth-child(7) > div:nth-child(1) > div.service__description > div.service__two-column > div.fm-button:nth-child(2)",
    dominationDoesDescription: "#edit-ad-profile > div > div.price-data > div.services-list > div:nth-child(7) > div:nth-child(1) > div.service__description",
    finishButton: ".edit-container__btn > .fm-button > .colorful-primary",
    sucessModalLabel: "p[class='p mb-20']"
    
    //label[for*='acompanhantedoes']
    //div[name=neighborhood]
}